name: Feature request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the problem and your proposed solution. This helps maintainers and others discuss scope and design.
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve? Who is it for?
      placeholder: "I would like to ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this could work?
      placeholder: "Add a setting / new page / API that ..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you thought about (optional)
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Is this a small change or a larger effort? Would you be willing to contribute?
      placeholder: "Small / Medium / Large. I can help with ..."
